/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "system_config.h"
#include "system_definitions.h"
#include "HwConfig.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
uint32_t address;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "ConfigurationSettings", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Home", ID_BUTTON_0, 400, 175, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NCBack", ID_BUTTON_1, 10, 175, 60, 60, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 0, 470, 145, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ConfigurationSettings'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 20);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, GUI_FONT_13B_1);
    FRAMEWIN_SetText(hItem, "Configuration Settings");
    //
    // Initialization of 'Home'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'NCBack'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "Update");
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 200, "Configuration Item", GUI_TA_LEFT | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 268, "Value ", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
    // USER START (Optionally insert additional code for further widget initialization)
    uint8_t i;
    char tempBuffer[200];
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);    
    for(i = 0; i < CONFIG_ITEM_COUNT; i++)
    {
        LISTVIEW_SetItemText(hItem, 0, i, configItemsStrings[i]);
        if(i <= LAST_BOOL_CONFIG_ITEM_INDEX)
        {
            address = (uint32_t)(&configData.calibrationEnabled + i);
            if(*(&configData.calibrationEnabled + i) == false)
                sprintf(tempBuffer, "False");
            else
                sprintf(tempBuffer, "True");
        }else if(i <= LAST_UINT8_CONFIG_ITEM_INDEX)
        {
            address = *(&configData.showBatteryReadiness + i - 1 - LAST_BOOL_CONFIG_ITEM_INDEX);
            sprintf(tempBuffer, "%u", address);
        }else if(i <= LAST_UINT16_CONFIG_ITEM_INDEX)
        {
            address = *(&configData.qcountMinimum + ((i - 1 - LAST_UINT8_CONFIG_ITEM_INDEX)));
            sprintf(tempBuffer, "%u", address);
        }else if(i <= LAST_INT16_CONFIG_ITEM_INDEX)
        {                   
            address = *(&configData.primaryPressureCalibrationValue + ((i - 1 - LAST_UINT16_CONFIG_ITEM_INDEX)));
            sprintf(tempBuffer, "%i", address);
        }else if(i <= LAST_UINT32_CONFIG_ITEM_INDEX)
        {              
            address = *(&configData.idCode + ((i - 1 -LAST_INT16_CONFIG_ITEM_INDEX)));
            sprintf(tempBuffer, "%u", address);
        }else if(i <= LAST_ENUM_CONFIG_ITEM_INDEX)
        {
            if(configDataPtr->pipeConfiguration == CFG_EOT_TYPE_SINGLE_PIPE)
                sprintf(tempBuffer, "SINGLE PIPE");
            else
                sprintf(tempBuffer, "DUAL PIPE");
        }
        else //selectedItem <= LAST_STRING_CONFIG_ITEM_INDEX
        {
            sprintf(tempBuffer, configDataCharArrays[i - LAST_ENUM_CONFIG_ITEM_INDEX - 1]);   
        }
//        itoa(tempBuffer, i, 10);
        LISTVIEW_SetItemText(hItem, 1, i, tempBuffer);
        if( i < CONFIG_ITEM_COUNT - 1)
            LISTVIEW_AddRow(hItem, NULL);
    }
    LISTVIEW_SetAutoScrollV(hItem, 1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Home'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
          emWin_GuiScreenChange(EMWIN_APP_SCREEN_HOME_PAGE);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'NCBack'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
          emWin_GuiScreenChange( EMWIN_APP_SCREEN_TEXT_ALIGNMENT );
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateConfigurationSettings
*/
WM_HWIN CreateConfigurationSettings(void);
WM_HWIN CreateConfigurationSettings(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
